## 環境構築

AI を用いたコーディングをする以前に，環境構築をする必要があります．

- Git, GitHub 周り `git`, `gh`
- Python 周り `uv`
- Julia 周り `julia`
- Rust 周り `cargo`/`rustc`
- Node.js 周り `node`/`npm`/`npx`
- Docker 周り `docker`, `devcontainer`
- その他コマンド `tmux`, `htop`, `btm` を入れていく
- AI Agent の導入 `claude`, `codex`, `cursor`, `opencode`

---

## 注意事項

- Linux/WSL ユーザは管理者権限を持っているものとする(自分のマシンとか).
- macOS ユーザは [Homebrew](https://brew.sh/) を使用する.
- Windows ユーザは [Winget](https://learn.microsoft.com/ja-jp/windows/package-manager/winget/) を使用する.
  - Windows 11 であれば PowerShell を開けば `winget` が使える.
- Nix のようなパッケージマネージャを知っている人はこの講義の対象者ではないので勝手に環境構築をして遊ぶこと．
- すでに環境構築ができている方は読み流してよい．あくまでも参考程度に読んでほしい．

---

### WSL を導入する方法

Windows 11 であれば PowerShell を開けば WSL を経由することで Linux 環境を構築することができる．

```powershell
wsl.exe --install Ubuntu-24.04
```

PC 自体を再起動してから Ubuntu-24.04 をインストールする．

---

## Git のインストール

Linux/WSL

```sh
sudo apt-get install git tig
```

macOS

```sh
brew install git tig
```

Windows

```sh
winget install --id Git.Git --source winget
```

```sh
git config --global user.name "Your Name"
git config --global user.email "your.email@example.com"
```

---

## GitHub CLI `gh` のインストール

https://cli.github.com/ の案内に従う．

Linux/WSL

```sh
(type -p wget >/dev/null || (sudo apt update && sudo apt install wget -y)) \
	&& sudo mkdir -p -m 755 /etc/apt/keyrings \
	&& out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
	&& cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
	&& sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
	&& sudo mkdir -p -m 755 /etc/apt/sources.list.d \
	&& echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
	&& sudo apt update \
	&& sudo apt install gh -y
```

macOS

```sh
brew install gh
```

Windows

```sh
winget install -e --id GitHub.cli --source winget
```

`gh auth login` で GitHub アカウントと連携する

これで，GitHub のサービスを CLI から利用することができる．

---

## Python のインストール

[uv](https://docs.astral.sh/uv/) を使用する．

Linux/WSL

```sh
sudo apt-get install curl
curl -LsSf https://astral.sh/uv/install.sh | sh
```

macOS

```sh
brew install curl
curl -LsSf https://astral.sh/uv/install.sh | sh
```

Windows

```sh
winget install --id Astral-sh.uv --source winget
```

```sh
$ mkdir example
$ cd example
$ uv init
$ uv add numpy
$ uv run <your-script.py>
```

---

## Julia のインストール

https://julialang.org/downloads/ の案内に従う．

Linux/WSL/macOS

```sh
$ curl -fsSL https://install.julialang.org | sh
```

Windows

```powershell
PS> winget install --name Julia --id 9NJNWW8PVKMN -e -s msstore
```

## Rust のインストール

Linux/WSL/macOS

https://www.rust-lang.org/tools/install の案内に従う．


```sh
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

Windows

https://learn.microsoft.com/ja-jp/windows/dev-environment/rust/setup?tabs=winget の案内に従う．

管理者権限でPowerShell を開き，以下のコマンドを実行する．

```powershell
PS> winget install -e --source winget --id Microsoft.VisualStudio.2022.BuildTools `
  --accept-source-agreements `
  --accept-package-agreements `
  --override "--wait --passive --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended"
```

通常のPowerShell で以下のコマンドを実行する．

```powershell
PS> winget install Rustlang.Rustup --source winget
```

動作確認

```sh
$ cargo new hello-world
$ cd hello-world
$ cargo run --release
cargo run --release
   Compiling hello-world v0.1.0 (path/to/your-workspace/hello-world)
    Finished `release` profile [optimized] target(s) in 1.38s
     Running `target/release/hello-world`
Hello, world!
```

---

## Node.js のインストール

NodeJS は JavaScript の実行環境であり，npm を使用することで JavaScript のパッケージを管理することができる．

https://nodejs.org/ja/download/ の案内に従う．

Linux/WSL/macOS

```sh
# nvmをダウンロードしてインストールする：
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.7/install.sh | bash
# シェルを再起動する代わりに実行する
\. "$HOME/.nvm/nvm.sh"
# Node.jsをダウンロードしてインストールする：
nvm install 24
# Node.jsのバージョンを確認する：
node -v # "v24.21.0"が表示される。
# npmのバージョンを確認する：
npm -v # "11.19.0"が表示される。
```

Windows

```powershell
PS> winget install --id OpenJS.NodeJS.LTS --source winget
```

```powershell
PS> node -v
PS> npm -v
```

---

## その他ベンチコマンドのインストール

Linux/WSL/macOS

```sh
sudo apt-get install tmux htop ripgrep
```

macOS

```sh
brew install tmux htop rg
```

Windows

参考: [psmuxでWindows 11＋PowerShellでtmux](https://qiita.com/charon/items/4ec359cd8a9d0d4f0b84) by `@charon` に従い，`tmux` をインストールする．

```powershell
PS> winget install psmux --source winget
```

Windows は `htop` の代わりに `btm` を使用する．

```powershell
PS> winget install Clement.bottom --source winget
```

---

## Docker のインストール

### Docker (`docker`)

Codex はユーザからの許可をバイパスするオプションを備えている．たとえば `--yolo` といったオプションだ．このようなオプションは便利だが 原理的には `rm -rf /` のような危険なコマンドの実行も許すことになる．このような状況を防ぐためにサンドボックス環境を使うのが望ましい．たとえば Docker が提供するコンテナはマウントするファイルを制御することで制限された範囲で AI Agent を行動させることが可能である．

OS に応じてインストールすること:

- [Install Docker Desktop on Mac](https://docs.docker.com/desktop/setup/install/mac-install/)
- [Install Docker Engine on Linux(Ubuntu)](https://docs.docker.com/engine/install/ubuntu/)
- [Install Docker Desktop on Windows](https://docs.docker.com/desktop/setup/install/windows-install/)


動作確認は下記のコマンドでできる:

```sh
$ docker run --rm hello-world
```

---

## DevContainer のインストール

[https://code.visualstudio.com/docs/devcontainers/devcontainer-cli](https://code.visualstudio.com/docs/devcontainers/devcontainer-cli) を参考にすること．CLI は `npm` を使用してインストールする．

Linux/WSL/macOS/Windows

```sh
$ npm install -g @devcontainers/cli
```

または Cursor または VS Code の拡張機能から DevContainer をインストールする．

---

## AI Agent の導入

どれか好きなのをインストールすれば良い．基本的に有料プランを前提とするので無料版に関しては説明しない．20ドルプランがあれば十分である．

### Claude Code

[https://code.claude.com/docs/en/overview](https://code.claude.com/docs/en/overview) を参考にすること

Linux/WSL/macOS

```sh
curl -fsSL https://claude.ai/install.sh | bash
```

Windows

```powershell
irm https://claude.ai/install.ps1 | iex
```

### OpenAI Codex

[https://learn.chatgpt.com/docs/codex/cli#getting-started](https://learn.chatgpt.com/docs/codex/cli#getting-started) を参考にすること

Linux/WSL/macOS

```sh
curl -fsSL https://chatgpt.com/codex/install.sh | sh
```

Windows

```powershell
powershell -ExecutionPolicy ByPass -c "irm https://chatgpt.com/codex/install.ps1 | iex"
```

### OpenCode

[https://opencode.ai/v2/docs](https://opencode.ai/v2/docs) を参考にすること

Linux/WSL/macOS

```sh
curl -fsSL https://opencode.ai/v2/install | bash
```

Windows ユーザは `Download a standalone CLI binary for your platform.` からバイナリをダウンロードして使う

### Cursor

[https://cursor.com/download](https://cursor.com/download) からダウンロードしてインストールする．

### VS Code

[https://code.visualstudio.com/download](https://code.visualstudio.com/download) からダウンロードしてインストールする．

GitHub Copilot を通して AI Agent を利用することができる．
